# Generated by Django 5.1.6 on 2026-08-30 15:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('starts_at', models.DateTimeField(verbose_name='Дата и время начала')),
                ('duration_minutes', models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длительность (мин)')),
                ('capacity', models.PositiveIntegerField(help_text='Максимальное число участников.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вместимость')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workshops', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Мастер-класс',
                'verbose_name_plural': 'Мастер-классы',
                'ordering': ['starts_at'],
            },
        ),
    ]
